# This file was generated by GoReleaser. DO NOT EDIT.
class Artisan < Formula
  desc "The build orchestrator for monorepositories and complex codebases"
  homepage "https://github.com/unravela/artisan"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/unravela/artisan/releases/download/v0.0.2/artisan_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "f0cb36ccb94ac0bcabaf7683a22762f4a997fec118ce74ebfa7a80e46ef4c8ee"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/unravela/artisan/releases/download/v0.0.2/artisan_0.0.2_Linux_x86_64.tar.gz"
      sha256 "fb5e95d50ca379ce08d5e9797007ac51f94d1c76d6bb9d8aa089a780501bce9e"
    end
  end

  def install
    bin.install "artisan"
  end
end
