# This file was generated by GoReleaser. DO NOT EDIT.
class Artisan < Formula
  desc "The build orchestrator for monorepositories and complex codebases"
  homepage "https://github.com/unravela/artisan"
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/unravela/artisan/releases/download/v0.0.8/artisan_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "fc2804c924a641946a646ab244f16de66514a33d8a91ac5f7827f02ecfad19c7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/unravela/artisan/releases/download/v0.0.8/artisan_0.0.8_Linux_x86_64.tar.gz"
      sha256 "3458d306b7e29e5af5ad8b2dea981dc84a7795bd99d4c162eb8b23c8a6c5e77f"
    end
  end

  def install
    bin.install "artisan"
  end
end
