# This file was generated by GoReleaser. DO NOT EDIT.
class Envgit < Formula
  desc "runs another command with env. variables loaded from file placed in git repository"
  homepage "https://github.com/unravela/envgit"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/unravela/envgit/releases/download/v0.1.0/envgit_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "92eb1da718daae88a5109a90438f792429a25d4eebe4a1ada4fe0bbd3cf5574e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/unravela/envgit/releases/download/v0.1.0/envgit_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6d1c6cb800132f182564e01eb8da2f5ff2b7aad6c9ada3a921de60fc7c0e9feb"
    end
  end

  def install
    bin.install "envgit"
  end
end
