# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwrk < Formula
  desc "A small CLI tool that helps you with monthly reports by extracting working hours directly from git repository."
  homepage "https://github.com/unravela/gitwrk"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/unravela/gitwrk/releases/download/v1.0.6/gitwrk_1.0.6_Darwin_x86_64.tar.gz"
    sha256 "5f5781bc7711071c52d7ccc39257b7b6636f0ff1f1d797a17e641e6598b8d94a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/unravela/gitwrk/releases/download/v1.0.6/gitwrk_1.0.6_Linux_x86_64.tar.gz"
      sha256 "678b19dc4120ab3ac007e523cccc4f18ef521879c3a8d241b96c6af7c076a8f8"
    end
  end

  def install
    bin.install "gitwrk"
  end
end
